App\DTO\TrickDTO:
    properties:
        title:
            - NotBlank:
                message: Le champs titre est obligatoire.

            - Length:
                max: 50
                maxMessage: Maximun 50 caract√®res.

        description:
            - NotBlank:
                message: Le champs description est obligatoire.

